# Read more https://github.com/actions/labeler

# Add 'repo' label to any root file changes
repo:
  - "*"

"@boonya/ts-monorepo-playground-first":
  - package/first/**

"@boonya/ts-monorepo-playground-second":
  - package/second/**

"@boonya/ts-monorepo-playground-third":
  - package/third/**

test:
  - "**/*.test.js"

"github-workflow":
  - ".github/workflows/*"
