name: "Setup env."
description: "Setup environment"

runs:
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
    - run: npm set '//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}'
    - run: npm ci
