name: Release

on:
  registry_package:
    types: [published]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "npm_metadata: ${{ toJSON(github.event.registry_package.package_version.npm_metadata) }} .\n"
          echo "name: ${{ toJSON(github.event.registry_package.package_version.npm_metadata.name) }} .\n"
          echo "version: ${{ toJSON(github.event.registry_package.package_version.npm_metadata.version) }} .\n"
          echo "registry_package: ${{ toJSON(github.event.registry_package) }} .\n"

  # build:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "release.tar.gz,foo/*.txt"
  #       bodyFile: "body.md"
