name: Assign PR

on:
  workflow_dispatch: # 👈 For debugging purpose
  workflow_call:
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
