name: Canary Release

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publishing 🚀
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm set '//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}'
      - run: npm ci
      - run: npm run build
      - run: |
          lerna publish --canary --yes \
            --preid canary \
            --pre-dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
