name: Draft a Release

on:
  push:
    branches:
      - main
    paths:
      - packages/*/package.json

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: boonya/gh-action-name-generator@main
        with:
          style: lowerCase
          separator: "-"
          length: 3
          seed: ${{ github.sha }}
        id: generated-tag
      - uses: boonya/gh-action-name-generator@main
        with:
          style: capital
          separator: " "
          length: 3
          seed: ${{ github.sha }}
        id: generated-name
      - run: |
          echo "Generated name is ${{ steps.generated-name.outputs.name }}."
          echo "Generated tag is ${{ steps.generated-tag.outputs.name }}."
      - uses: release-drafter/release-drafter@v5.21.1
        with:
          name: ${{ steps.generated-name.outputs.name }}
          tag: ${{ steps.generated-tag.outputs.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
