name: Draft a Release

on:
  push:
    branches:
      - main
    paths:
      - packages/*/package.json

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: boonya/gh-action-name-generator@main
        with:
          style: lowerCase
          separator: "-"
          seed: ${{ github.sha }}
        id: generatedTag
      - uses: boonya/gh-action-name-generator@main
        with:
          style: capital
          separator: ' '
          seed: ${{ github.sha }}
        id: generatedName
      - run: |
          echo "Generated name is ${{ steps.generatedName.outputs.name }}."
          echo "Generated tag is ${{ steps.generatedTag.outputs.name }}."
      - uses: release-drafter/release-drafter@v5.21.1
        with:
          name: "${{ steps.generatedName.outputs.name }}"
          tag: "${{ steps.generatedTag.outputs.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
