name: Pre-Release 🚚

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      distTag:
        description: "Package distribution tag aka. dist-tag."
        required: true
        default: test
        type: choice
        options:
          - alpha
          - beta
          - prerelease
          - rc
          - test

jobs:
  # test:
  #   name: Test
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  publish:
    # needs: test
    runs-on: ubuntu-latest
    name: Publishing 🚀
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm set '//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}'
      - run: npm ci
      - run: npm run build
      - uses: changesets/action@v1
        with:
          version: changeset version --snapshot
          publish: changeset publish
          # --snapshot ${{ inputs.distTag }}
          # --tag ${{ inputs.distTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
